server:
  port: 8081

spring:
  datasource:
    url: ${LOCAL_POSTGRES_HOST}/${LOCAL_POSTGRES_DB}?prepareThreshold=0&targetServerType=primary
    username: ${LOCAL_POSTGRES_USR}
    password: ${LOCAL_POSTGRES_PWD}

springdoc:
  api-docs:
    enabled: true

management:
  endpoint:
    health:
      show-details: always