server:
  port: 8081

spring:
  datasource:
    url: ${LOCAL_POSTGRES_HOST}/${LOCAL_POSTGRES_DB}?prepareThreshold=0&targetServerType=primary
    username: ${LOCAL_POSTGRES_USR}
    password: ${LOCAL_POSTGRES_PWD}

  jpa:
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    enabled: true

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
